#!/bin/bash
source config.cfg
source functions

action=$1
pidFile=./pid

function pid {
  echo $(< $pidFile)
}

function isRunning {
  ps -p "$(pid)" > /dev/null
}

function stopApp {
  log "Stopping $APP_NAME" true
  if isRunning; then
    kill -9 "$(pid)"
  else
    log "$APP_NAME not running" true
  fi
}

function startApp {
  log "---"
  log "Starting $APP_NAME $(version)" true
  sh ./main >> $LOG_FILE 2>&1 & echo $! > "$pidFile" &
}

case $action in
  start)
    if isRunning; then
      stopApp
      startApp
    else
      startApp
    fi
    ;;
  stop)
    stopApp
    ;;
  status)
    if isRunning; then
      echo "$APP_NAME: Running!"
    else
      echo "$APP_NAME: Not running"
    fi
    ;;
  version)
    echo $(version)
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
    exit 1
    ;;
esac

