#!/bin/bash

function log {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
  [ $2 ] && echo $1
}

function seconds_since_epoch {
  echo $(date +%s)
}

function notify {
  NEXT_ALERT_TIME=${NEXT_ALERT_TIME:-0}
  if [ "$NEXT_ALERT_TIME" -le "$(seconds_since_epoch)" ]; then
    now=$(seconds_since_epoch)
    $NOTIFICATION_STICKY && sticky="-s"
    growlnotify -n "$APP_NAME" $sticky -m "$1" $APP_NAME
    if [ "$?" -eq  "0" ]; then
      NEXT_ALERT_TIME=$(($now + $NOTIFICATION_DELAY_TIME))
      log "Notify: $1"
    else
      log "Notify failed: $1"
    fi
  else
    log "Notify (not sent): $1"
  fi
}

