#!/bin/bash

function log {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
  [ $2 ] && echo $1
}

function seconds_since_epoch {
  echo $(date +%s)
}

function notify {
  if [ "$NEXT_ALERT_TIME" -le "$(seconds_since_epoch)" ]; then
    now=$(seconds_since_epoch)
    NEXT_ALERT_TIME=$(($now + $NOTIFICATION_DELAY_TIME))
    growlnotify -n "$APP_NAME" -s -m "$1" $APP_NAME
    echo "Notify: $1"
  else
    echo "Notify (not sent): $1"
  fi
}

