#!/bin/bash
source config.cfg
source functions

while [ true ]
do
  BATTERY_STATUS=$(battery_percentage)
  log "Current battery charge: $BATTERY_STATUS%, $(charge_state)"

  if is_min_charge $BATTERY_STATUS && ! is_charging; then
    notify "Minimum battery charge reached"
  elif is_max_charge $BATTERY_STATUS && is_charging; then
    notify "Maximum battery charge reached"
  fi

  if [ -r $SCHEDULE_FILE ]; then
    while IFS=, read time_read percentage message
    do
      [ -z $time_read ] && continue
      time_now=$(date +%s)
      time_expire=($time_now + $NOTIFICATION_DELAY_TIME)
      time_scheduled=$(date -jf "%H:%M" "$time_read" +%s)
      # Compare date witin 5 minutes and percentage-wise
      if [ $BATTERY_STATUS -le $percentage ] && [ $time_scheduled -ge $time_now ] && [ $time_scheduled -le $time_expire ]; then
        notify "$message"
      fi
    done < $SCHEDULE_FILE
  fi

  sleep $INTERVAL
done

