#!/bin/bash
source config.cfg
source functions

while [ true ]
do
  # see: http://hints.macworld.com/article.php?story=20100130123935998
  BATTERY_STATUS=$(batteryPercentage)
  isCharging=$(isBatteryCharging)
  log "Current battery charge: $BATTERY_STATUS%, $(batteryChargeState)"

  if [ "$BATTERY_STATUS" -le "$MIN_STATUS" ] && [[ ! $isCharging ]]; then
    notify "Minimum battery charge reached"
  elif [ "$BATTERY_STATUS" -ge "$MAX_STATUS" ] && [[ $isCharging ]]; then
    notify "Maximum battery charge reached"
  fi

  if [ -r $SCHEDULE_FILE ]; then
    while IFS=, read timeRead percentage message
    do
      [ -z $timeRead ] && continue
      timeNow=$(date +%s)
      timeExpire=($timeNow + $NOTIFICATION_DELAY_TIME)
      timeScheduled=$(date -jf "%H:%M" "$timeRead" +%s)
      # Compare date witin 5 minutes and percentage-wise
      if [ $BATTERY_STATUS -le $percentage ] && [ $timeScheduled -ge $timeNow ] && [ $timeScheduled -le $timeExpire ]; then
        notify "$message"
      fi
    done < $SCHEDULE_FILE
  fi

  sleep $INTERVAL
done

